services:
  postgres:
    image: postgres:latest
    container_name: agro-farm_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql
  redis:
    image: redis:7.4.7-alpine
    container_name: agro-farm_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
